### ISSUE TITLE
[Bug] Create new note doest not work under Linux

### ISSUE THREAD

**Issue by frudolph77** [madeindjs/vscode-notable#5]
Hello,

first of all, thank you for your great extension.

When you create an new note under Linux, the file will be created in the root-directory, because of the, by `uri.parse` added, `/` in front of the filename. 
The root director is equivalent to `C:` under Windows.
But a normal user has no write permissions there, therefor saving the file fails and an additional empty `untitled.md` tab gets opened.

It's mandatory to add the users home directory in front of the filename. Unfortunately i did not figure out how to obtain it.

kind regards
Frank

**Comment by madeindjs** [comment]
Hello, thanks for your feedback, it's really appreciated :hugs: . I create a fix which be published soon ;)
